### ISSUE TITLE
images from resource pack not displaying

### ISSUE THREAD

**Issue by MarcD57** [jthistle/mc-paintings#113]
I've redone the painting using MC Painting Creator and created the new MCPACK. When I add the resource pack i don't see thew new paintings, only the the ones from previous attempt.

**Comment by jthistle** [comment]
If you rename the new MCPACK to `[yourpackname].zip` and unzip it, do you see the new images in it, or is it still the old ones?

If you see the __new__ images after you unzip it, then you need to check that you have loaded the resource pack into Minecraft correctly - perhaps the old one is still loaded?

If you instead see the __old__ images, then tell me and we can try to work out why.

**Comment by MarcD57** [comment]
I double clicked the .mcpack file and Minecraft opened it
I removed the old image resource packs and activated the new one
When I launch Minecraft and add painting the previous ones show up and not the new ones

**Comment by jthistle** [comment]
Can you rename the new `.mcpack` file to be a `.zip` file and unzip it? Then, please tell me whether or not it has the new images in it.

**Comment by MarcD57** [comment]
I got it to open properly now I had to remove the files from the main menu and then reinstall
Thank you for your help
Located at

**Comment by jthistle** [comment]
Glad you could sort it.
