### ISSUE TITLE
Add save project

### ISSUE THREAD

**Issue by minintamvan** [jthistle/mc-paintings#50]
when pressed backers or whatever is, and reset the painting when go back
sorry man rip english

**Comment by jthistle** [comment]
Ah, I get you. So that your hard work isn't erased when you quickly click over to another page? Yeah.

A save function might be a little difficult to implement. I will happily implement a warning when you're about to lose work, though. Thanks for the suggestion!

**Comment by jthistle** [comment]
fixed in 73234c7806318ac655a12f1f1926d30654a3fdde
