### ISSUE TITLE
Can't use more than one custom painting

### ISSUE THREAD

**Issue by Bookwizard1216** [jthistle/mc-paintings#94]
On my survival world by the way I'm on bedrock edition I can't use more then one custom painting in the world but I really want like a collection of paintings but that will not be possible if I can only have a single custom painting texture pack without involving cheats so I can get achievements what do I do

**Comment by jthistle** [comment]
Hi! Thanks for getting in touch. From what you've said, I can't really work out what might be wrong. Would you be able to email me your resource pack? My address is jtspam38 at gmail dot com. Please comment once you have done this.

**Comment by jthistle** [comment]
I'm closing this for now due to lack of activity.
